package config

const (
	ALERT_METHOD_EMAIL   = 0
	ALERT_METHOD_KAFKA   = 1
	ALERT_METHOD_DISCORD = 2
	ALERT_METHOD_SMS     = 3

	ALERT_TYPE_INFO  = 0
	ALERT_TYPE_WARN  = 1
	ALERT_TYPE_ERROR = 2
	ALERT_TYPE_DEBUG = 3
)
